
ios:
	gomobile bind -ldflags=-w -target=ios github.com/ipfs/go-ipfs/cmd/ipfs_mobile

android:
	gomobile bind -ldflags=-w -target=android github.com/ipfs/go-ipfs/cmd/ipfs_mobile

clean:
	rm -rf Ipfsmobile.framework
	rm -rf ipfsmobile.aar